### PR TITLE
Fix #2333: implement hash-based caching for execp to persist scroll state

### LINKED ISSUE #2333: [Bug]: ${scroll} does not work from within Bash file
### What happened?

When i execute a bash file withing conky with `${execp bashfile.sh}` the scroll function doesn't work! It shows the text but is not scrolling.

```
echo "\${scroll wait 10 1 6 This text needs to be scrolled, but does not!}"
```

### Version

1.19.8

### Which OS/distro are you seeing the problem on?

Ubuntu

### Conky config

```Lua
conky.config = {
    background = false,
    alignment = 'top_middle',
    gap_x = -900,
    gap_y = -428,
    minimum_width = 400,.
    minimum_height = 100,
    no_buffers = true,
    double_buffer = true,
    text_buffer_size = 2048,
    draw_borders = false,
    draw_outline = false,
    draw_shades = false,
    draw_graph_borders = false,
    uppercase = false,
    out_to_stderr = false,
    own_window = true,
    own_window_title = 'conky-mediaplayer',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_type = 'normal',
    own_window_hints = 'undecorated,below,skip_taskbar,skip_pager',
    use_xft = true,
    font = 'Liberation Sans:size=7',
    xftalpha = 1,
    override_utf8_locale = true,
    update_interval = 0.3,
    default_color = 'white',
    imlib_cache_size = 10000,
    imlib_cache_flush_interval = 60,
    lua_load = './image.lua ./time-bar.lua',
    lua_draw_hook_pre = 'main_bars',
};

conky.text = [[
${execp ./player.sh}
${execi 1 ./cover.sh}
#${exec bash ./click_event.sh} # > /dev/null 2>&1}
]];
```

### Stack trace

```GDB

```

### Relevant log output

```Shell

```

### PR DESCRIPTION
**Pull request by harshal24-chavan**
# Checklist
- [x] I have described the changes
- [x] I have linked to any relevant GitHub issues, if applicable
- [ ] Documentation in `doc/` has been updated
- [x] All new code is licensed under GPLv3

## Description
This PR implements hash-based caching to persist the scroll state.
Fixes #2333

* Describe the changes, why they were necessary, etc
1. Added a `last_execp_hash` member to the text_object. 
2. In src/data/exec.cc, I modified fill_p to compare the current output hash with the `last_execp_hash` hash.
3. If the hash matches, the existing object tree (obj->sub) is preserved. We call `extract_variable_text_internal` and `generate_text_internal` on the existing tree instead of re-parsing.

* Describe how the changes will affect existing behaviour.
1. For ${scroll}: It now persists its animation state and "circles/loops" correctly even when inside an execp call.
2. For other variables: Dynamic variables (like ${cpu}) still update correctly because extract_variable_text_internal is called every cycle

* Describe how you tested and validated your changes.
1. Environment: Tested on Arch Linux (Kernel 6.x).
2. Verified that a ${scroll} inside a bash script loops matches the timing of a standard static scroll.
3. Dynamic Update: Verified that changing the bash script output triggers a re-parse (due to hash mismatch) and updates the display immediately
4. Stability: Monitored via bpytop; memory remained stable at ~15MB with no leaks detected over an extended period. CPU usage remained consistent.
5. Style: Code was formatted using clang-format according to the project's .clang-format specification.

* Include any relevant screenshots/evidence demonstrating that the changes work and have been tested.

### CODE REVIEW

File: src/data/exec.cc [hunk 1]
```diff
@@ -225,11 +226,24 @@ static inline double get_barnum(const char *buf) {
 void fill_p(const char *buffer, struct text_object *obj, char *p,
             unsigned int p_max_size) {
   if (obj->parse) {
-    evaluate(buffer, p, p_max_size);
+    size_t current_hash = std::hash<std::string>{}(buffer);
+
+    if (obj->last_execp_hash == std::numeric_limits<size_t>::max() ||
```
Comment (Caellian) [inline src/data/exec.cc]: This check is wrong.

You initialize with `size_t last_execp_hash = std::numeric_limits<size_t>::max()`, but you don't actually - the code that constructs `text_object` uses `malloc` and `memset(0)`.

There's no difference between 0 and max sentinel (hash is equally likely to be either), so you should just simplify this check to check for zero.

File: src/content/text_object.h [hunk 2]
```diff
@@ -121,6 +121,9 @@ struct text_object {
   } data;
 
   void *special_data;
+
+  size_t last_execp_hash =
+      std::numeric_limits<size_t>::max(); /* caching-hash for execp content*/
```
Comment (Caellian) [inline src/content/text_object.h]: and remove initializer here (doesn't get used so it's confusing).

File: src/data/exec.cc [hunk 3]
```diff
@@ -225,11 +226,24 @@ static inline double get_barnum(const char *buf) {
...
+        current_hash != obj->last_execp_hash) {
+      if (obj->sub) {
+        free_text_objects(obj->sub);
+        delete obj->sub;
+      }
+      obj->sub = new text_object{};
```
Comment (Caellian) [inline src/data/exec.cc]: Don't use `new` here. It's good C++ code, but the old code isn't, so you're mixing allocation strategies - older code uses `malloc` and `free`. If some other code calls free instead of delete on this it might blow up.

File: src/content/text_object.h [hunk 4]
```diff
@@ -121,6 +121,9 @@ struct text_object {
   } data;
 
   void *special_data;
+
+  size_t last_execp_hash =
```
Comment (Caellian) [inline src/content/text_object.h]: Also, this shouldn't live on every `text_object` when only `execp` needs it. Move it into `execi_data` which is unique per-exec variable and won't bloat all text objects..

**Review by Caellian — CHANGES_REQUESTED** [review]

File: src/data/exec.cc (hunk 1 above)
Comment (harshal24-chavan) [reply src/data/exec.cc]: Thanks for your reviews, I'll get to work on these and update the PR.

**Comment by Lowrida** [comment]
So is this problem now solved or.. ?

**Review by Caellian — DISMISSED** [review]
I told you:

> Also, this shouldn't live on every `text_object` when only `execp` needs it. Move it into `execi_data` which is unique per-exec variable and won't bloat all text objects..

I was wrong. This caused UB because `execp` without interval actually allocated a `char *` instead of `execi_data`. So I fixed it on your branch.

I just need your ok on merging this because I manufactured history and marked you as the author of the squashed and modified commit. Squash was preparation for fast-forward, and I just wanted to streamline the process and reduce back-and-forth. Review the diff on your commit and let me know whether it's what you would've written (`text_object` works and is fine).

My commit on top is just reducing technical debt that modifying `text_object` would introduce and some 10 year old code that prevented you from using `execi_data` in the first place (which is a slightly better choice).

You can revert your commits from a [bundle](https://github.com/user-attachments/files/27110542/original-commits.zip) or locally with `git reset --hard 4fbddbe8fa56767b2664dc47a5c5737eea6b5dda`, if you want them back for any reason.

**Comment by harshal24-chavan** [comment]
@Caellian 

OK from my side. The changes look good.

Thank you for the refactor and for cleaning everything up!

**Comment by Caellian** [comment]
Np, I planned on fast-forwarding these two commits instead of squashing because they're separate changes and either can introduce bugs on its own. Had I done that without modifying your commit they would've been coupled due to the UB.

This seems good to fast-forward, but I need @brndnmtthws to approve on my commit now :sweat_smile:.

**Review by brndnmtthws — APPROVED** [review]
