### PR TITLE
Fix non-text content using `own_window_argb_value`

### LINKED ISSUE #1504: [Bug]: Bars use `own_window_argb_value` for transparency, text doesn't
### What happened?

https://github.com/brndnmtthws/conky/issues/1497

The bars aren't displayed from the cores under wayland

### Version

conky 1.19.1_pre compiled 2023-04-10 for Linux x86_64

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

_No response_

### Stack trace

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Caellian**
Closes #1504.

`own_window_argb_value` shouldn't control content color.

Also fixed `clear_text` using a wrong cairo operator.

Tested on hyprland.

### CODE REVIEW

File: src/display-wayland.cc [hunk 1]
```diff
@@ -784,9 +784,6 @@ void display_output_wayland::cleanup() {
 
 void display_output_wayland::set_foreground_color(Colour c) {
   current_color = c;
-#ifdef BUILD_ARGB
-  current_color.alpha = own_window_argb_value.get(*state);
-#endif /* BUILD_ARGB */
```
Comment (Caellian) [inline src/display-wayland.cc:789]: Transparent bars caused by this.

File: src/display-wayland.cc [hunk 2]
```diff
@@ -926,8 +923,9 @@ void display_output_wayland::clear_text(int exposures) {
 
   cairo_set_source_rgba(window->cr, color.red / 255.0, color.green / 255.0,
                         color.blue / 255.0, color.alpha / 255.0);
-  cairo_set_operator(window->cr, CAIRO_OPERATOR_SOURCE);
-  cairo_paint(window->cr);
+  cairo_set_operator(window->cr, CAIRO_OPERATOR_CLEAR);
+  cairo_rectangle(window->cr, 0, 0, window->rectangle.width(),
+                  window->rectangle.height());
```
Comment (Caellian) [inline src/display-wayland.cc:928]: This seems more correct - [SO answer](https://stackoverflow.com/a/53253583/3837417).

Resetting to `OVER` isn't needed because of `cairo_restore`.

**Review by brndnmtthws — APPROVED** [review]

**Comment by Caellian** [comment]
#2127 fixes omission of `cairo_fill` in this PR.
