### PR TITLE
Fix scrolling of UTF-8 text.

### LINKED ISSUE #223: Conky scroll multibyte character splitting
I run i3 WM in arch. I feed/pipe conky into my i3bar, which is great. Runs great.
However, when listing the filename of songs, i3bar sometimes gives me:
json lexical error invalid bytes in utf8 string conky
I have found that by removing the scrolling part, I no longer have this issue. However, many of the names are extremely long, so this is inconvenient.
I saw mentioned there was an issue at one point with conky splitting characters mid-byte. Personally, I don't care if the whole name displays perfectly all the time, as long as it doesn't crash my i3 bar.
I'll attach my config.
I honestly assumed this issue would already be on here, but as I don't see it, I'll create one.

[i3conkyrc.txt](https://github.com/brndnmtthws/conky/files/162555/i3conkyrc.txt)

### PR DESCRIPTION
**Pull request by AlexeyBond**
Fix issue #129 (UPD: should fix #223 and #45 too).

Port of PR #292 to master with fixes for new scroll modes.

+ right scroll now works with color changes

### CODE REVIEW

**Comment by Erinor2** [comment]
Hello Alexey,

Will #377 also be fixed?

Regards,
Philippe

File: src/conky.h [hunk 1]
```diff
@@ -298,6 +298,12 @@ void generate_text_internal(char *, int, struct text_object);
 int percent_print(char *, int, unsigned);
 void human_readable(long long, char *, int);
 
+#ifdef BUILD_X11
```
Comment (AlexeyBond) [inline src/conky.h]: Variable `utf8_mode` is defined inside of `#ifdef BUILD_X11 ... #endif` in `conky.cc`, so if it will be used when `BUILD_X11` is not defined then the program won't link.

File: src/scroll.cc [hunk 2]
```diff
@@ -35,6 +35,51 @@
 #include "x11.h"
 #include <vector>
 
+/**
+ * Length of a character in bytes.
+ * @param c first byte of the character
+ */
+inline int scroll_character_length(char c) {
+#ifdef BUILD_X11
```
Comment (AlexeyBond) [inline src/scroll.cc]: (see answer to comment above)

Scroll still will work in console mode, but without UTF-8 support.

File: src/scroll.cc [hunk 3]
```diff
@@ -35,6 +35,51 @@
...
+#endif
+
+	return 1;
+}
+
+/**
+ * Check if a byte should be skipped when counting characters to scroll text to right.
+ */
+inline bool scroll_check_skip_byte(char c) {
+#ifdef BUILD_X11
```
Comment (AlexeyBond) [inline src/scroll.cc]: (see responses to comments above)

File: src/scroll.cc [hunk 4]
```diff
@@ -50,6 +95,45 @@ struct scroll_data {
...
+/**
+ * Get count of characters to right from (sd->start) position.
+ */
+static unsigned int scroll_count_characters_to_right(struct scroll_data* sd, const std::vector<char>& buf) {
+    unsigned int n = 0;
+    int offset = sd->start;
+
+    while ('\0' != buf[offset]) {
+        offset += scroll_character_length(buf[offset]);
+        ++n;
```
Comment (AlexeyBond) [inline src/scroll.cc]: Fixed.

File: src/scroll.cc [hunk 5]
```diff
@@ -50,6 +95,45 @@ struct scroll_data {
...
+    }
+
+    return n;
+}
+
+static void scroll_scroll_left(struct scroll_data* sd, const std::vector<char>& buf, unsigned int amount) {
+    for (int j = 0; (j < amount) && (buf[sd->start] != '\0'); ++j) {
```
Comment (AlexeyBond) [inline src/scroll.cc]: Fixed.

File: src/scroll.cc [hunk 6]
```diff
@@ -50,6 +95,45 @@ struct scroll_data {
...
+        sd->start += scroll_character_length(buf[sd->start]);
+    }
+
+    if(buf[sd->start] == 0 || (unsigned) sd->start > strlen(&(buf[0]))) {
```
Comment (AlexeyBond) [inline src/scroll.cc]: Fixed.

File: src/conky.h (hunk 1 above)
Comment (ght) [inline src/conky.h]: My bad, didn't notice that.

File: src/scroll.cc [hunk 7]
```diff
@@ -111,11 +108,11 @@ static unsigned int scroll_count_characters_to_right(struct scroll_data* sd, con
 }
 
 static void scroll_scroll_left(struct scroll_data* sd, const std::vector<char>& buf, unsigned int amount) {
-    for (int j = 0; (j < amount) && (buf[sd->start] != '\0'); ++j) {
+    for (int i = 0; (i < amount) && (buf[sd->start] != '\0') && (sd->start < buf.size()); ++i) {
         sd->start += scroll_character_length(buf[sd->start]);
     }
 
-    if(buf[sd->start] == 0 || (unsigned) sd->start > strlen(&(buf[0]))) {
+    if (buf[sd->start] == 0 || sd->start > strlen(buf.data())) {
```
Comment (ght) [inline src/scroll.cc]: Not sure, but as far as I understand it would be safer to use `strnlen` instead of `strlen`.

Comment (AlexeyBond) [inline src/scroll.cc]: In [conky.cc#891](https://github.com/brndnmtthws/conky/blob/master/src/conky.cc#L891)(function `generate_text_internal` that generates content of `buf`) there is a `'\0'` written to the end of buffer, so if there is any unsafe call to `strlen` then that's [conky.cc#885](https://github.com/brndnmtthws/conky/blob/master/src/conky.cc#L885).

Comment (ght) [inline src/scroll.cc]: Right, didn't see that.
